#COMENTARIO DE APENAS UMA LINHA É #

#AQUI É UM COMENTÁRIO DE UMA LINHA

'''
    ISTO É CHAMADO DE DOCSTRING E O PYTHON LÊ ESSAS LINHAS

    ESTE É UM COMENTÁRIO MULTILINHA; CONTUDO, ISTO NÃO É UM COMENTÁRIO
'''

#este é o comando para imprimir dados na tela
print(123456)